const stockActionTypes = {
  ADD_STOCK_START: 'ADD_STOCK_START',
  ADD_STOCK_SUCCESS: 'ADD_STOCK_SUCCESS',
  ADD_STOCK_FAILURE: 'ADD_STOCK_FAILURE',
  EMPTY_ERROR: 'EMPTY_ERROR',
  RESET_SUCCESS: 'RESET_SUCCESS'
};
export default stockActionTypes;