const shopActionTypes = {
  ADD_WAREHOUSE_START: 'ADD_WAREHOUSE_START',
  ADD_WAREHOUSE_SUCCESS: 'ADD_WAREHOUSE_SUCCESS',
  ADD_WAREHOUSE_FAILURE: 'ADD_WAREHOUSE_FAILURE',
  EMPTY_ERROR: 'EMPTY_ERROR',
  RESET_SUCCESS: 'RESET_SUCCESS'
};
export default shopActionTypes;