const enterpriseActionTypes = {
  ADD_ENTERPRISE_START: 'ADD_ENTERPRISE_START',
  ADD_ENTERPRISE_SUCCESS: 'ADD_ENTERPRISE_SUCCESS',
  ADD_ENTERPRISE_FAILURE: 'ADD_ENTERPRISE_FAILURE',
  EMPTY_ERROR: 'EMPTY_ERROR',
  RESET_SUCCESS: 'RESET_SUCCESS'
};
export default enterpriseActionTypes;